# Generated by Django 5.2 on 2025-04-03 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hyzmat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=15, null=True)),
                ('salgy', models.TextField(blank=True, null=True)),
                ('suraty', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('ulanyjy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Toleg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mukdar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('senesi', models.DateField(auto_now_add=True)),
                ('toleg_usuly', models.CharField(choices=[('nagt', 'Nagt'), ('nagt dal', 'Nagt Däl')], max_length=20)),
                ('hyzmat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tolegler.hyzmat')),
                ('ulanyjy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
