# Generated by Django 5.2 on 2025-04-03 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolegler', '0002_alter_hyzmat_options_alter_profil_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habarlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady', models.CharField(max_length=50, unique=True)),
                ('goylan_senesi', models.DateTimeField(auto_now_add=True)),
                ('beyany', models.TextField(blank=True, null=True)),
                ('goyan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Habarlar',
            },
        ),
    ]
