# Generated by Django 5.2 on 2025-04-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolegler', '0003_habarlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='habarlar',
            name='suraty',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
