# Generated by Django 5.2 on 2025-04-04 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolegler', '0004_habarlar_suraty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='doglan_guni',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='ulanyjy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL),
        ),
    ]
